-- MySQL Script generated by MySQL Workbench
-- Tue Jun  6 10:47:18 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cartorioapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cartorioapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cartorioapp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cartorioapp` ;

-- -----------------------------------------------------
-- Table `cartorioapp`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartorioapp`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `cpf` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `senha` VARCHAR(100) NULL,
  `data_hora` DATETIME NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartorioapp`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartorioapp`.`pedido` (
  `pedido_id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('Certidão', 'Procuração', 'Testamento') NULL,
  `ato` ENUM('Procuração', 'Escritura', 'Outro') NULL,
  `livro` VARCHAR(45) NULL,
  `folha` VARCHAR(45) NULL,
  `outorgante` VARCHAR(100) NULL,
  `outorgado` VARCHAR(100) NULL,
  `data_hora` DATETIME NULL,
  `usuario_id` INT NULL,
  `status` ENUM('Aguardando', 'Em análise', 'Pronto', 'Entregue', 'Cancelado') NULL,
  `rg` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `casamento` VARCHAR(45) NULL,
  PRIMARY KEY (`pedido_id`),
  INDEX `fk_certidao_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_certidao_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cartorioapp`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartorioapp`.`movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartorioapp`.`movimentacao` (
  `movimentacao_id` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NULL,
  `usuario_id` INT NULL,
  `data_hora` DATETIME NULL,
  `sequencia` INT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`movimentacao_id`),
  INDEX `fk_movimentacao_pedido_idx` (`pedido_id` ASC),
  INDEX `fk_movimentacao_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_movimentacao_pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `cartorioapp`.`pedido` (`pedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentacao_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cartorioapp`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartorioapp`.`log_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartorioapp`.`log_status` (
  `log_status_id` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NULL,
  `data_hora` DATETIME NULL,
  `status_antigo` ENUM('Aguardando', 'Em análise', 'Pronto', 'Entregue', 'Cancelado') NULL,
  `status_novo` ENUM('Aguardando', 'Em análise', 'Pronto', 'Entregue', 'Cancelado') NULL,
  `usuario_int` INT NULL,
  `ip` VARCHAR(45) NULL,
  PRIMARY KEY (`log_status_id`),
  INDEX `fk_log_status_usuario_idx` (`usuario_int` ASC),
  CONSTRAINT `fk_log_status_usuario`
    FOREIGN KEY (`usuario_int`)
    REFERENCES `cartorioapp`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartorioapp`.`log_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartorioapp`.`log_session` (
  `log_session` INT NOT NULL,
  `usuario_id` INT NULL,
  `ip` VARCHAR(45) NULL,
  `data_hora` DATETIME NULL,
  PRIMARY KEY (`log_session`),
  INDEX `fk_log_session_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_log_session_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cartorioapp`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartorioapp`.`auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartorioapp`.`auth` (
  `auth_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `tipo` ENUM('facebook', 'google') NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`auth_id`),
  INDEX `fk_auth_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_auth_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cartorioapp`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartorioapp`.`firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartorioapp`.`firma` (
  `firma_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `cpf` VARCHAR(45) NULL,
  `data_hora` DATETIME NULL,
  PRIMARY KEY (`firma_id`))
ENGINE = InnoDB;

USE `cartorioapp` ;


-- -----------------------------------------------------
-- View `cartorioapp`.`vw_firma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cartorioapp`.`vw_firma`;
USE `cartorioapp`;
CREATE  OR REPLACE VIEW `vw_firma` AS SELECT nome,cpf FROM firma;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
